services:
  # Database service
  mysql_portfolio:
    image: reins21/mysql-csc:latest
    restart: always
    ports:
      - "3309:3306"  # Host port 3307 mapped to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: rein
      MYSQL_PASSWORD: pass123
    volumes:
      - mysql_portfolio:/var/lib/mysql

  # WordPress (image based on Apache)
  wordpress:
    depends_on:
      - mysql_portfolio
    image: reins21/wordpress-csc:latest
    restart: always
    ports:
      - "8221:80"
    environment:
      WORDPRESS_DB_HOST: mysql_portfolio:3306  # Connecting to MySQL on port 3306 inside the container
      WORDPRESS_DB_USER: rein
      WORDPRESS_DB_PASSWORD: pass123
      WORDPRESS_DB_NAME: wordpress_database
    volumes:
      - wp-portfolio:/var/www/html

volumes:
  mysql_portfolio: {}
  wp-portfolio: {}
